version: '3.8'
services:  
    game:
        user: 1000:1000
        build:
            context: ./game
            target: base
        volumes:
            - ./game:/game
        ports:
          - 8080:8080